### PR TITLE
Fixed docker installation and NUC 12 firmware

### PR DESCRIPTION
**Pull request by dsimog01**
@3alpha has updated docker installation process and @dsimog01 has added firmware needed for the NUC 12 to detect the network card properly.

### CODE REVIEW

**Comment by dsimog01** [comment]
There is still an error shown related to the file iwl-debug-yoyo.bin, which is missing because it does not exist, but this is a bug which should not affect the system (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966218, https://forums.debian.net/viewtopic.php?t=149817). The fix proposed does not remove the error message

**Comment by pablomendezroyo** [comment]
would be great to report here tests for each feature:
- wifi in intel nuc 12
- new docker installation process

**Comment by dsimog01** [comment]
> So even
> 
> ```
> apt -t bullseye-backports install -y linux-image-amd64 linux-firmware-nonfree
> ```
> 
> doesn't work for installing firmware?

Nope, I have tested that again right now and it is not enough, I still need to install files from git.kernel.org

**Comment by dsimog01** [comment]
This branch includes too many changes, each branch should be merged independently. I am closing the PR.

**Pull request closed without merging**
