### PR TITLE
Voss build 3 16 23

### PR DESCRIPTION
**Pull request by alexpeterson91**
@dsimog01 I havent been able to make this work in a little bit now and am oddly getting the same errors about permissions for the `generate_dappnode_debian_iso.sh` both when running it with GHA and locally.  i added this one line to the first ISO script making the one above executable and it started working

### CODE REVIEW

**Review by dsimog01 — COMMENTED** [review]
I'd say it LGTM, even though it could be a bit more permission-restrictive I'd say. However, you should try to avoid adding noisy commits to the PRs (like the one for reverting accident). I think @3alpha is your man for approving this.

**Comment by alexpeterson91** [comment]
Honestly it's for this experimental branch only not trying to worry about the main repo right now. This will all be gonzo when Debian 12 is out anyway but I need to get this out. My last trey I published and installed all fine latest versions of everything too. Wi-Fi worked LAN worked but dappnode commands didn't. Could connect to Wi-Fi but not my.dappnode and couldn't get vpn credentials as root or normal user directly connected to it. Docker ps shows core packages look fine. But I can't make WireGuard credentials or run any docker commands weird.

**Comment by alexpeterson91** [comment]
Just wanted to make sure it's fine for this branch right now.

**Comment by alexpeterson91** [comment]
> However, you should try to avoid adding noisy commits to the PRs (like the one for reverting accident).

Yeah I really regret that happening. I was trying to commit to a new branch and then my cat stepped on my hand on my keyboard and it just pushed the change to your branch. I was trying to keep it on a new branch I created so I could test it but my cat had other plans. I actually even pulled the Ethernet adapter from my laptop immediately to try and stop it from going through but it happened too fast.

**Comment by pablomendezroyo** [comment]
@dsimog01 @alexpeterson91 what is the current status of this PR?

Looks like a PR for an experimental branch, please remove this PR if not necessary, stop opening PRs with no activity on them

**Pull request closed without merging**
